# Site settings
title: Project Wilberforce Website
email: projectwilberforce@gmail.com
description: We make the virtual world a better place.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://projectwilberforce.github.io" # the base hostname & protocol for your site
twitter_username: wilberforcefx
github_username:  projectwilberforce
repository: projectwilberforce/projectwilberforce.github.io

comments:
    disqus: "wilberforcefx"

links:
  - github: "https://github.com/projectwilberforce/"
  - twitter: "https://twitter.com/wilberforcefx/"
  - reddit: "https://www.reddit.com/user/WilberforceFX/"
 # - youtube: "https://www.youtube.com/user/me"